services:
  db:
    image: postgres:15
    environment:
      POSTGRES_DB: mynotes
      POSTGRES_USER: user
      POSTGRES_PASSWORD: pass
    volumes:
      - db_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  backend:
    build: ./backend
    ports:
      - "3001:3001"
    environment:
      DB_NAME: mynotes
      DB_USER: user
      DB_PASSWORD: pass
      DB_HOST: db
    depends_on:
      - db

  frontend:
    build: ./frontend
    ports:
      - "3000:3000"
    depends_on:
      - backend

volumes:
  db_data:
